name = "earthly-worker"
main = "./build/worker.mjs"
compatibility_date = "2024-05-01"

[build]
command = "powershell ./scripts/windows/build_wasm_tinygo.ps1"

[[rules]]
type = "Data"
globs = ["**/*.jpg"]
fallthrough = false
