name: Build and push release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Install hub
        run: |
          sudo apt-get update && sudo apt-get install -y hub
      - name: Install swagger
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
      - name: Build docs
        run: |
          swag init -d "./" -g ./cmd/server/main.go -o ./build/docs
      - name: Build releases
        run: |
          go build -o ./earthly_server ./cmd/server
          go build -o ./earthly_cli ./cmd/cli
      - name: Zip and upload release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          export tag_name="${GITHUB_REF##*/}"
          zip ./earthly-linux-${tag_name}.zip ./earthly_server ./earthly_cli ./build/equirectangular/* ./build/docs/*
          hub release create -a ./earthly-linux-${tag_name}.zip "${tag_name}" -m "Release ${tag_name}"
